name: Keep Render Backend Alive

on:
  schedule:
    - cron: "*/5 * * * *" # Runs every 5 minutes

jobs:
  keep-alive:
    runs-on: windows-latest
    steps:
      - name: Send request to Render backend
        run: |
          Invoke-WebRequest -Uri "https://kingdom-h7lf.onrender.com/" -UseBasicParsing
